version: "3.7"

services:
  web:
    restart: unless-stopped
    image: nginx
    volumes:
      - ./:/var/www:delegated
      - ./server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - dev
  db:
    restart: always
    image  : mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./var:/var/www/var
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - "3306:3306"
    networks:
       - dev
  php:
   restart: unless-stopped
   image: misoko/php-fpm-8.0.8:1.0
   depends_on:
     - db
   volumes:
    - .:/var/www:delegated
   networks:
     - dev
   environment:
     DATABASE_URL: mysql://root:@db:/freelance?mysql=8.0.25

  mail:
    image: mailhog/mailhog
    ports:
      - 1080:8025
    networks:
      dev:
networks:
  dev:

volumes:
  db-data: