version: "3.7"

services:
  web:
    restart: unless-stopped
    image: nginx
    container_name: nginx-xpressrun
    volumes:
      - ./:/var/www:delegated
      - ./server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - dev
  db:
    restart: always
    image  : mysql
    container_name : mysql-xpressrun
    volumes:
      - db-data:/var/lib/mysql
      - ./var:/var/www/var
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - "3306:3306"
    networks:
       - dev

  php:
   restart: unless-stopped
   container_name: php-fpm
   image: misoko/php-fpm-8.0.8:1.0
   depends_on:
     - db
   volumes:
    - .:/var/www:delegated
   networks:
     - dev
   environment:
     DATABASE_URL: mysql://root:@db:/xpressRun_test?mysql=8.0.25
     MERCURE_PUBLISH_URL: http://mercure:3000/.well-known/mercure
  mercure:
    restart: unless-stopped
    container_name: mercure-xpressrun
    depends_on:
      - php
    image: dunglas/mercure:legacy-latest
    environment:
      CORS_ALLOWED_ORIGINS: '*'
      ADDR: ":3000"
      PUBLISHER_JWT_KEY: 'ChangeMe'
      SUBSCRIBER_JWT_KEY: 'ChangeMe'
      ALLOW_ANONYMOUS: 1
    ports:
      -  "3000:3000"
    networks:
      - dev
  mail:
    image: mailhog/mailhog
    ports:
      - 1080:8025
    networks:
      dev:
networks:
  dev:

volumes:
  db-data: